-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           10.1.13-MariaDB - mariadb.org binary distribution
-- OS do Servidor:               Win32
-- HeidiSQL Versão:              10.3.0.5771
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


CREATE TABLE IF NOT EXISTS `history_list` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_conta` int(11) NOT NULL,
  `id_char` int(11) NOT NULL,
  `nick` varchar(100) CHARACTER SET latin1 NOT NULL,
  `id_item` int(11) NOT NULL,
  `categoria` varchar(100) CHARACTER SET latin1 NOT NULL,
  `qtde` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           5.6.48-log - MySQL Community Server (GPL)
-- OS do Servidor:               Win64
-- HeidiSQL Versão:              10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `users_shadow` (
  `roleid` int(11) NOT NULL DEFAULT '0',
  `userid` int(11) NOT NULL,
  `name` varchar(200) NOT NULL,
  `race` varchar(200) NOT NULL,
  `occupation` varchar(200) NOT NULL,
  `gender` varchar(200) NOT NULL,
  `custom_data_size` varchar(200) NOT NULL,
  `custom_stamp` varchar(200) NOT NULL,
  `status` varchar(200) NOT NULL,
  `delete_time` varchar(200) NOT NULL,
  `create_time` varchar(200) NOT NULL,
  `lastlogin_time` varchar(200) NOT NULL,
  `forbid_size` varchar(200) NOT NULL,
  `level` varchar(200) NOT NULL,
  `level2` varchar(200) NOT NULL,
  `exp` varchar(200) NOT NULL,
  `sp` varchar(200) NOT NULL,
  `pp` varchar(200) NOT NULL,
  `hp` varchar(200) NOT NULL,
  `mp` varchar(200) NOT NULL,
  `posx` varchar(200) NOT NULL,
  `posy` varchar(200) NOT NULL,
  `posz` varchar(200) NOT NULL,
  `worldtag` varchar(200) NOT NULL,
  `money` varchar(200) NOT NULL,
  `invader_state` varchar(200) NOT NULL,
  `invader_time` varchar(200) NOT NULL,
  `pariah_time` varchar(200) NOT NULL,
  `factionid` varchar(200) NOT NULL,
  `factionrole` varchar(200) NOT NULL,
  `reputation` varchar(200) NOT NULL,
  `custom_status_size` varchar(200) NOT NULL,
  `filter_data_size` varchar(200) NOT NULL,
  `charactermode_size` varchar(200) NOT NULL,
  `instancekeylist_size` varchar(200) NOT NULL,
  `dbltime_expire` varchar(200) NOT NULL,
  `dbltime_mode` varchar(200) NOT NULL,
  `dbltime_begin` varchar(200) NOT NULL,
  `dbltime_used` varchar(200) NOT NULL,
  `dbltime_max` varchar(200) NOT NULL,
  `time_used` varchar(200) NOT NULL,
  `timestamp` varchar(200) NOT NULL,
  `storesize` varchar(200) NOT NULL,
  `petcorral_size` varchar(200) NOT NULL,
  `vitality` varchar(200) NOT NULL,
  `energy` varchar(200) NOT NULL,
  `strength` varchar(200) NOT NULL,
  `agility` varchar(200) NOT NULL,
  `max_hp` varchar(200) NOT NULL,
  `max_mp` varchar(200) NOT NULL,
  `hp_gen` varchar(200) NOT NULL,
  `mp_gen` varchar(200) NOT NULL,
  `walk_speed` varchar(200) NOT NULL,
  `run_speed` varchar(200) NOT NULL,
  `swim_speed` varchar(200) NOT NULL,
  `flight_speed` varchar(200) NOT NULL,
  `attack` varchar(200) NOT NULL,
  `damage_low` varchar(200) NOT NULL,
  `damage_high` varchar(200) NOT NULL,
  `attack_speed` varchar(200) NOT NULL,
  `attack_range` varchar(200) NOT NULL,
  `damage_low0` varchar(200) NOT NULL,
  `damage_low1` varchar(200) NOT NULL,
  `damage_low2` varchar(200) NOT NULL,
  `damage_low3` varchar(200) NOT NULL,
  `damage_low4` varchar(200) NOT NULL,
  `damage_high0` varchar(200) NOT NULL,
  `damage_high1` varchar(200) NOT NULL,
  `damage_high2` varchar(200) NOT NULL,
  `damage_high3` varchar(200) NOT NULL,
  `damage_high4` varchar(200) NOT NULL,
  `damage_magic_low` varchar(200) NOT NULL,
  `damage_magic_high` varchar(200) NOT NULL,
  `resistance0` varchar(200) NOT NULL,
  `resistance1` varchar(200) NOT NULL,
  `resistance2` varchar(200) NOT NULL,
  `resistance3` varchar(200) NOT NULL,
  `resistance4` varchar(200) NOT NULL,
  `defense` varchar(200) NOT NULL,
  `armor` varchar(200) NOT NULL,
  `max_ap` varchar(200) NOT NULL,
  `var_data_size` varchar(200) NOT NULL,
  `skills_size` varchar(200) NOT NULL,
  `storehousepasswd_size` varchar(200) NOT NULL,
  `waypointlist_size` varchar(200) NOT NULL,
  `coolingtime_size` varchar(200) NOT NULL,
  `storehouse_money` varchar(200) NOT NULL,
  `storehouse_size` varchar(200) NOT NULL,
  `inventory_size` varchar(200) NOT NULL,
  `equipment_size` varchar(200) NOT NULL,
  `taskinventory_size` varchar(200) NOT NULL,
  `task_data_size` varchar(200) NOT NULL,
  `task_complete_size` varchar(200) NOT NULL,
  `reincarn_times` varchar(200) NOT NULL,
  `reincarn_maxlevel` varchar(200) NOT NULL,
  `realm_level` varchar(200) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- Copiando dados para a tabela dbo.users_shadow: 5.525 rows
/*!40000 ALTER TABLE `users_shadow` DISABLE KEYS */;
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(16, 16, '"cls0gender0"', '0', '0', '0', '0', '0', '1', '', '', '2019-09-12 22:23:56', '0', '150', '32', '0', '99999999', '0', '4545', '2727', '478.6', '218.9', '188.9', '1', '100000000', '0', '0', '0', '0', '0', '0', '0', '4', '0', '960', '0', '0', '1568001600', '0', '28800', '14737', '72', '80', '5', '5', '5', '605', '150', '4545', '2727', '3', '2', ' 2.0', ' 7.0', ' 3.0', ' 5.0', '0', '150', '150', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '399', '64', '904', '0', '146', '8', '0', '0', '0', '0', '0', '136', '4', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(17, 16, '"cls9gender1"', '0', '9', '1', '0', '0', '1', '', '', '2012-11-21 00:21:45', '0', '1', '0', '0', '0', '0', '50', '70', '-2417.9', '134.9', '-3062.3', '1', '0', '0', '0', '0', '0', '0', '0', '0', '4', '0', '932', '0', '0', '1353258000', '0', '21600', '537', '14', '16', '5', '5', '5', '5', '5', '50', '70', '1', '4', ' 2.0', ' 4.8', ' 3.0', ' 5.0', '0', '1', '1', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', '64', '40', '0', '2', '8', '0', '0', '1', '1', '0', '0', '0', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(18, 16, '"cls8gender0"', '0', '8', '0', '0', '0', '1', '', '', '2012-11-21 00:21:30', '0', '1', '0', '0', '0', '0', '75', '45', '-2581.0', '136.0', '-3026.1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '4', '0', '932', '0', '0', '1353258000', '0', '21600', '1531', '19', '16', '5', '5', '5', '5', '5', '75', '45', '3', '2', ' 2.0', ' 5.0', ' 3.0', ' 5.0', '0', '1', '1', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', '64', '28', '0', '2', '8', '0', '0', '1', '1', '0', '0', '0', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(19, 16, '"cls1gender1"', '0', '1', '1', '0', '0', '1', '', '', '2019-09-12 22:24:24', '0', '150', '22', '0', '109999998', '0', '3030', '14672', '476.1', '221.0', '151.3', '1', '30000000', '0', '0', '0', '0', '0', '0', '0', '4', '0', '960', '0', '0', '1568001600', '0', '28800', '5138', '46', '80', '5', '5', '750', '5', '5', '3030', '14672', '1', '4', ' 2.0', ' 4.8', ' 3.0', ' 5.0', '0', '31', '31', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '150', '150', '0', '0', '0', '0', '0', '1', '0', '399', '64', '700', '0', '146', '8', '0', '0', '0', '0', '0', '104', '8', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(20, 16, '"cls2gender0"', '0', '2', '0', '0', '0', '1', '', '', '2015-03-31 21:20:59', '0', '1', '0', '0', '0', '0', '50', '70', '2559.8', '216.1', '-3403.2', '1', '0', '0', '0', '0', '0', '0', '0', '0', '4', '0', '932', '0', '0', '1353258000', '0', '21600', '423', '7', '16', '5', '5', '5', '5', '5', '50', '70', '1', '4', ' 2.0', ' 4.8', ' 3.0', ' 5.0', '0', '1', '1', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', '64', '40', '0', '2', '8', '0', '0', '1', '1', '0', '0', '0', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(21, 16, '"cls2gender1"', '0', '2', '1', '0', '0', '1', '', '', '', '0', '1', '0', '0', '0', '0', '50', '70', '2623.0', '225.0', '-3407.0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '5', '5', '5', '5', '50', '70', '-1075842064', '0', ' 0.0', '-1.7', ' 0.0', ' 0.0', '0', '1', '1', '136265260', ' 0.0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(22, 16, '"cls3gender0"', '1', '3', '0', '0', '0', '1', '', '', '', '0', '1', '0', '0', '0', '0', '60', '60', '332.0', '241.0', '3068.0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '5', '5', '5', '5', '60', '60', '0', '0', ' 0.0', ' 0.0', ' 0.0', ' 0.0', '0', '1', '1', '0', ' 0.0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(23, 16, '"cls3gender1"', '1', '3', '1', '0', '0', '1', '', '', '2019-09-12 22:24:49', '0', '150', '32', '0', '99999999', '0', '3636', '12036', '467.6', '217.9', '186.5', '1', '130000000', '0', '0', '0', '0', '0', '0', '0', '4', '0', '960', '0', '0', '1568001600', '0', '28800', '3132', '36', '80', '5', '5', '705', '50', '5', '3636', '12036', '2', '3', ' 2.0', ' 5.1', ' 3.0', ' 5.0', '0', '91', '91', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '91', '91', '0', '0', '0', '0', '0', '1', '0', '399', '64', '700', '0', '146', '8', '0', '0', '0', '0', '0', '168', '4', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(24, 16, '"cls4gender0"', '2', '4', '0', '0', '0', '1', '', '', '2019-09-12 22:25:06', '0', '150', '22', '0', '99999999', '0', '5151', '2121', '469.9', '218.0', '186.9', '1', '140042311', '0', '0', '0', '0', '0', '0', '0', '4', '0', '960', '0', '0', '1568001600', '0', '28800', '3122', '38', '80', '5', '5', '5', '505', '250', '5151', '2121', '4', '1', ' 2.0', ' 5.0', ' 3.0', ' 5.0', '0', '150', '150', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '399', '64', '688', '0', '146', '8', '0', '0', '0', '0', '0', '8', '4', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(25, 16, '"cls4gender1"', '2', '4', '1', '0', '0', '1', '', '', '', '0', '1', '0', '0', '0', '0', '85', '35', '332.0', '241.0', '3068.0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '5', '5', '5', '5', '85', '35', '0', '0', ' 0.0', ' 0.0', ' 0.0', ' 0.0', '0', '1', '1', '0', ' 0.0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(26, 16, '"cls5gender0"', '3', '5', '0', '0', '0', '1', '', '', '', '0', '1', '0', '0', '0', '0', '65', '50', '2623.0', '225.0', '-3407.0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '5', '5', '5', '5', '65', '50', '-1075842064', '0', ' 0.0', '-1.7', ' 0.0', ' 0.0', '0', '1', '1', '136265260', ' 0.0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(27, 16, '"cls5gender1"', '3', '5', '1', '0', '0', '1', '', '', '2020-02-25 18:12:20', '0', '1', '0', '0', '0', '0', '65', '50', '2559.4', '216.2', '-3406.1', '135', '0', '0', '0', '0', '0', '0', '0', '0', '4', '0', '960', '0', '0', '1582516800', '0', '14400', '242', '5', '16', '5', '5', '5', '5', '5', '65', '50', '3', '2', ' 2.0', ' 5.2', ' 3.0', ' 5.0', '0', '1', '1', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', '64', '28', '0', '2', '8', '0', '0', '0', '0', '0', '8', '4', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(28, 16, '"cls6gender0"', '4', '6', '0', '0', '0', '1', '', '', '2019-09-12 22:25:22', '0', '150', '32', '0', '99999999', '0', '46981', '4983', '455.2', '221.3', '153.8', '1', '129999984', '0', '0', '0', '0', '0', '0', '0', '4', '0', '960', '0', '0', '1568001600', '0', '28800', '4402', '38', '80', '5', '5', '5', '50', '705', '3939', '3333', '3', '2', ' 2.0', ' 5.2', ' 3.0', ' 5.0', '0', '150', '150', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '399', '64', '616', '0', '146', '8', '0', '0', '0', '0', '0', '8', '4', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(29, 16, '"cls6gender1"', '4', '6', '1', '0', '0', '1', '', '', '', '0', '1', '0', '0', '0', '0', '65', '55', '332.0', '241.0', '3068.0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '5', '5', '5', '5', '65', '55', '0', '0', ' 0.0', ' 0.0', ' 0.0', ' 0.0', '0', '1', '1', '0', ' 0.0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(30, 16, '"cls7gender0"', '5', '7', '0', '0', '0', '1', '', '', '', '0', '1', '0', '0', '0', '0', '30', '50', '332.0', '241.0', '3068.0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '10', '25', '5', '10', '30', '50', '135870208', '-1210298380', '-0.0', ' 0.0', '-1.3', ' 0.0', '0', '1', '1', '135144543', '-0.0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(31, 16, '"cls7gender1"', '5', '7', '1', '0', '0', '1', '', '', '2019-09-12 22:25:37', '0', '150', '22', '0', '99999999', '0', '3030', '14672', '473.2', '218.2', '187.5', '1', '147143504', '0', '0', '0', '0', '0', '0', '0', '4', '0', '960', '0', '0', '1568001600', '0', '28800', '3333', '31', '80', '5', '5', '750', '5', '5', '3030', '14672', '1', '4', ' 2.0', ' 4.8', ' 3.0', ' 5.0', '0', '31', '31', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '150', '150', '0', '0', '0', '0', '0', '1', '0', '399', '64', '724', '0', '146', '8', '0', '0', '0', '0', '0', '104', '4', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(1024, 1024, '"zdark"', '4', '6', '0', '176', '0', '1', '', '2019-09-12 22:32:47', '2020-03-01 04:01:56', '0', '150', '22', '0', '81512677', '0', '45404', '4983', '505.8', '222.3', '133.7', '1', '200000000', '0', '0', '0', '0', '0', '0', '0', '4', '8', '960', '0', '0', '1582516800', '0', '50400', '611687', '1403', '80', '995', '5', '5', '50', '705', '3939', '3333', '3', '2', ' 2.0', ' 5.2', ' 3.0', ' 5.0', '0', '150', '150', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '399', '64', '616', '0', '146', '8', '0', '4', '47', '22', '0', '168', '16', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(1025, 1024, '"zdarkEA"', '4', '6', '0', '176', '1', '1', '', '2019-09-15 01:30:56', '2019-10-03 22:03:46', '0', '150', '32', '0', '99999999', '0', '3939', '3333', '484.8', '220.5', '165.4', '1', '129999984', '0', '0', '0', '0', '0', '0', '0', '4', '0', '960', '0', '0', '1569816000', '0', '28800', '4890', '39', '80', '5', '5', '5', '50', '705', '3939', '3333', '3', '2', ' 2.0', ' 5.2', ' 3.0', ' 5.0', '0', '150', '150', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '399', '64', '616', '0', '146', '8', '0', '0', '0', '0', '0', '72', '4', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(1026, 1024, '"zdarkWB"', '2', '4', '0', '176', '0', '1', '', '2019-09-15 01:31:14', '2020-02-16 10:57:37', '0', '150', '22', '0', '99999999', '0', '5151', '2121', '482.7', '220.1', '181.4', '1', '140042311', '0', '0', '0', '0', '0', '0', '0', '4', '0', '960', '0', '0', '1581307200', '0', '50400', '6642', '47', '80', '5', '5', '5', '505', '250', '5151', '2121', '4', '1', ' 2.0', ' 5.0', ' 3.0', ' 5.0', '0', '150', '150', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '399', '64', '688', '0', '146', '8', '0', '0', '0', '0', '0', '136', '4', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(1027, 1024, '"zdarkEP"', '5', '7', '1', '176', '0', '1', '', '2020-02-16 11:47:14', '2020-02-26 20:25:28', '0', '150', '22', '0', '99999999', '0', '3030', '14672', '513.6', '221.7', '140.0', '1', '147143504', '0', '0', '0', '0', '0', '0', '0', '4', '8', '960', '0', '0', '1582516800', '0', '21600', '16643', '65', '80', '5', '5', '750', '5', '5', '3030', '14672', '1', '4', ' 2.0', ' 4.8', ' 3.0', ' 5.0', '0', '31', '31', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '150', '150', '0', '0', '0', '0', '0', '1', '0', '399', '64', '724', '0', '146', '8', '0', '0', '0', '0', '0', '136', '4', '', '', '');
INSERT INTO `users_shadow` (`roleid`, `userid`, `name`, `race`, `occupation`, `gender`, `custom_data_size`, `custom_stamp`, `status`, `delete_time`, `create_time`, `lastlogin_time`, `forbid_size`, `level`, `level2`, `exp`, `sp`, `pp`, `hp`, `mp`, `posx`, `posy`, `posz`, `worldtag`, `money`, `invader_state`, `invader_time`, `pariah_time`, `factionid`, `factionrole`, `reputation`, `custom_status_size`, `filter_data_size`, `charactermode_size`, `instancekeylist_size`, `dbltime_expire`, `dbltime_mode`, `dbltime_begin`, `dbltime_used`, `dbltime_max`, `time_used`, `timestamp`, `storesize`, `petcorral_size`, `vitality`, `energy`, `strength`, `agility`, `max_hp`, `max_mp`, `hp_gen`, `mp_gen`, `walk_speed`, `run_speed`, `swim_speed`, `flight_speed`, `attack`, `damage_low`, `damage_high`, `attack_speed`, `attack_range`, `damage_low0`, `damage_low1`, `damage_low2`, `damage_low3`, `damage_low4`, `damage_high0`, `damage_high1`, `damage_high2`, `damage_high3`, `damage_high4`, `damage_magic_low`, `damage_magic_high`, `resistance0`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `defense`, `armor`, `max_ap`, `var_data_size`, `skills_size`, `storehousepasswd_size`, `waypointlist_size`, `coolingtime_size`, `storehouse_money`, `storehouse_size`, `inventory_size`, `equipment_size`, `taskinventory_size`, `task_data_size`, `task_complete_size`, `reincarn_times`, `reincarn_maxlevel`, `realm_level`) VALUES
	(1028, 1024, '"zdarkWR"', '0', '0', '0', '176', '0', '1', '', '2020-02-23 05:10:39', '2020-02-26 18:54:36', '0', '150', '32', '0', '99999999', '0', '4545', '2727', '516.1', '221.2', '151.2', '1', '100000000', '0', '0', '0', '0', '0', '0', '0', '4', '8', '960', '0', '0', '1582516800', '0', '21600', '19752', '85', '80', '5', '5', '5', '605', '150', '4545', '2727', '3', '2', ' 2.0', ' 7.0', ' 3.0', ' 5.0', '0', '150', '150', '16', ' 2.5', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '399', '64', '28', '0', '146', '8', '0', '0', '0', '0', '0', '136', '4', '', '', '');

/*!40000 ALTER TABLE `users_shadow` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
